### ISSUE TITLE
Accessability: To low contrast between "(affiliate link)" and background.

### ISSUE THREAD

**Issue by trickypr** [fivnex/fivnex.co#1]
Hi,

I hope you have been having a good day. Your website has an affiliate link on it that is to dark to be easily seen on the background. 

Screenshot of link:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/23250792/109585446-a70dc200-7b57-11eb-8a28-481fa2730113.png">

Contrast checker results:
[https://coolors.co/contrast-checker/383b43-272c2f](https://coolors.co/contrast-checker/383b43-272c2f)

**Comment by KaiTheCEO** [comment]
I will fix this later, due to the fact that I don't want to fuck with the CSS and potentially break everything.

**Comment by razetime** [comment]
Mind if I fix this?

**Comment by KaiTheCEO** [comment]
Yes, I just am too tired. You don't need to ask tho, @razetime you are a Fivnex staff member

**Comment by razetime** [comment]
Fixed in pull request #4. ^

**Comment by razetime** [comment]
Fix is now live: https://github.com/fivnex/fivnex.co/commit/2d93b4e824ec16770c73785123ca8251d599c794

**Comment by KaiTheCEO** [comment]
Still waiting to see changes, looks like there might be an issue to it. Not sure if it is just taking a while to update, or if my cache is messed up, but will check again

**Comment by KaiTheCEO** [comment]
Just checked in incognito, it works
