### ISSUE TITLE
Remove unused blogspot social button

### ISSUE THREAD

**Issue by razetime** [fivnex/fivnex.co#3]
The blogspot button in the footer links nowhere, and from my knowledge, we do not have a blogspot page.

Would be a good idea to remove it.

**Comment by razetime** [comment]
Fixed in pull request #4.

**Comment by KaiTheCEO** [comment]
We do have a blogspot page, it just was forgotten, my bad

**Comment by razetime** [comment]
For some reason the blog is put under `https=` instead of `href=`. anyway, it is fixed.
